kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pytest --cov=gewv_sides_client

- name: publish
  image: plugins/pypi
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
  failure: ignore